# Generated by Django 4.2.30 on 2026-10-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_dead_stock_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dead_stock_days',
            field=models.IntegerField(default=0, help_text='Mark as dead stock if no sale in this many days'),
        ),
        migrations.AlterField(
            model_name='product',
            name='minimum_stock_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='tax_percentage',
            field=models.IntegerField(default=0, help_text='GST %'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('Nos', 'Numbers'), ('Kg', 'Kilograms'), ('Ltr', 'Litres'), ('Mtr', 'Metres'), ('Box', 'Box'), ('Pcs', 'Pieces'), ('Set', 'Set'), ('Pair', 'Pair'), ('Dozen', 'Dozen'), ('Packets', 'Packets'), ('Cartoon', 'Cartoon'), ('Other', 'Other')], default='Nos', max_length=20),
        ),
    ]
