# Generated by Django 4.2.30 on 2026-10-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_dead_stock_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='reorder_level',
            field=models.IntegerField(default=0, help_text='Suggest reorder when stock falls below'),
        ),
    ]
