# Generated by Django 4.2.29 on 2026-09-24 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='salesperson',
            field=models.ForeignKey(blank=True, help_text='Sales person selected in POS', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_made', to=settings.AUTH_USER_MODEL),
        ),
    ]
