# Generated by Django 4.2.30 on 2026-10-01 10:06

from django.db import migrations, models
import django.db.models.deletion
import passes.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pass_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('token', models.CharField(db_index=True, default=passes.models.generate_pass_token, max_length=64, unique=True)),
                ('pass_type', models.CharField(blank=True, default='', max_length=50)),
                ('event_date_from', models.DateField(blank=True, null=True)),
                ('event_date_to', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('UNUSED', 'Unused'), ('REGISTERED', 'Registered'), ('BLOCKED', 'Blocked')], db_index=True, default='UNUSED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pass',
                'verbose_name_plural': 'Passes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('consent_given', models.BooleanField(default=False)),
                ('customer_photo_blob', models.CharField(max_length=500)),
                ('pass_photo_blob', models.CharField(max_length=500)),
                ('face_embedding', models.BinaryField()),
                ('face_quality_score', models.FloatField(default=0.0)),
                ('ocr_pass_number', models.CharField(blank=True, default='', max_length=50)),
                ('needs_review', models.BooleanField(default=False)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('pass_obj', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration', to='passes.pass')),
            ],
            options={
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='EntryLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scan_photo_blob', models.CharField(blank=True, default='', max_length=500)),
                ('similarity_score', models.FloatField(default=0.0)),
                ('result', models.CharField(choices=[('MATCHED', 'Matched'), ('NO_MATCH', 'No Match'), ('REVIEW', 'Review'), ('DUPLICATE', 'Duplicate Entry'), ('BLOCKED', 'Blocked')], db_index=True, max_length=20)),
                ('admitted', models.BooleanField(default=False)),
                ('scanned_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('device_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('pass_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entry_logs', to='passes.pass')),
            ],
            options={
                'ordering': ['-scanned_at'],
                'indexes': [models.Index(fields=['pass_obj', 'scanned_at'], name='passes_entr_pass_ob_2ea885_idx')],
            },
        ),
    ]
